function [cineq, ceq] = ConFcnWrapper(z, data,ref,Qp,Rp,Qt,Rt,distToCenter,safetyDistance)
p = 70;
nx = 3;
pnx = p*nx;
nu = 2;
nmv = 2;
Ts = 0.1;
p1 = p+1;
uz = z(p*nx+1:end-1);
X = zeros(p1,nx);
U = zeros(p1,nu);
Xz = reshape(z(1:p*nx), nx, p)';
Uz = reshape(uz,nmv,p)';
X(1,:) = data.state;
X(2:p1,:) = Xz;
U(1:p1-1,:) = Uz;
e = z(end);
cineq = parkingIneqConFcn(X,U,e,data,ref,Qp,Rp,Qt,Rt,distToCenter,safetyDistance);
ceq = zeros(pnx,1);
ic = 1:nx; 
Ui = U';
Xi = X';
h = Ts/2;
for i = 1:p
    uk  = Ui(:,i);
    xk  = Xi(:,i);
    xk1 = Xi(:,i+1);
    fk  = parkingVehicleStateFcn(xk,  uk, ref,Qp,Rp,Qt,Rt,distToCenter,safetyDistance);
    fk1 = parkingVehicleStateFcn(xk1, uk, ref,Qp,Rp,Qt,Rt,distToCenter,safetyDistance);
    ceq(ic) = xk + h*(fk + fk1) - xk1;
    ic = ic + nx;
end
end